
url: https://gluecklich-tools.github.io
baseurl: /einfach-geld-ordnen
title: "Einfach Geld ordnen"
description: "Einfaches Haushaltsbuch & Geld ordnen – statische Inhalte"

markdown: "kramdown"

plugins:
  - "jekyll-seo-tag"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - templates
  - 00_ARCHIV
  - 01_governance
  - tools
  - README.md
