# P0 Known Failure Gates - synced 20260502 V8 buyer-surface governance

$script:EGO_P0_KNOWN_FAILURES = @(
    'NO_BIG_INLINE_COMMAND',
    'FULLSWAP_ONLY',
    'NO_NAKED_STEP_OR_FILE_RUN',
    'TRUTH_FREEZE_REQUIRED',
    'CURRENT_TRUTH_TOP_BLOCK_REQUIRED',
    'TECHNICAL_PASS_IS_NOT_VISUAL_ACCEPTANCE',
    'SCREENSHOT_PASS_REQUIRED_FOR_VISIBLE_PRODUCT_ACCEPTANCE',
    'SCREENSHOT_TRUTH_BEATS_COUNTERS',
    'REJECT_EXCEL_REPAIR_PROMPT',
    'REJECTED_STAGE_NO_CONTINUATION',
    'STAGE_ONLY_BEFORE_ACTIVE_REPLACE',
    'NO_GLOBAL_USEDRANGE_CLEAR_AUTOFIT_UNMERGE_DELETE',
    'MERGE_SAFE_EXCEL_CLEANUP_REQUIRED',
    'ALLOW_EMPTY_COLLECTION_FOR_EMPTY_FINDINGS',
    'REQUIRED_READS_MATRIX_RUNNER_VALIDATESET_ATOMIC_SYNC',
    'LEAN_HANDOFF_ZIP_REQUIRED',
    'PUBLIC_PRIVATE_BOUNDARY_SCAN_BEFORE_COMMIT',
    'NO_MICROFIXING_VISIBLE_SURFACE',
    'ONE_SHEET_ONE_CONTRACT_ONE_ONESHOT_FINALIZER',
    'MAX_THREE_VISIBLE_FIXES_THEN_CONTRACT_REBUILD',
    'MAX_THREE_VISIBLE_FIXES_THEN_REBUILD_FROM_GROUND',
    'NO_V_CHAIN_WITHOUT_REBUILD_DECISION',
    'BUYER_SURFACE_CONTRACT_REQUIRED',
    'NO_INTERNAL_QA_LANGUAGE_ON_BUYER_SURFACE',
    'V8_BUYER_SURFACE_PENDING_APPLY_OR_RESULT_CONFIRMATION'
)

function Get-EgoP0KnownFailures {
    [CmdletBinding()]
    param()

    return $script:EGO_P0_KNOWN_FAILURES
}

function Test-EgoP0CurrentTruthText {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)][AllowEmptyString()][string]$Text,
        [string]$ExpectedHash = '0F68C27FC967F01AE9942E02812717FA83DAB0712363CC4C7E5DD6B292D7F392',
        [string]$ExpectedNext = 'APPLY_P0_VISIBLE_SURFACE_REBUILD_V8_BUYER_SURFACE_FROM_PLAN'
    )

    $required = @(
        'CURRENT_TRUTH=V8_PENDING_APPLY_OR_V8_RESULT_PENDING_CONFIRMATION',
        'TARGET_SHEETS=PARAMETER|STEUER|SPARZIELE',
        $ExpectedHash,
        $ExpectedNext,
        'NO_MICROFIXING=ENFORCED',
        'MAX_3_CORRECTIONS_THEN_REBUILD=ENFORCED',
        'TECHNICAL_PASS_IS_NOT_VISUAL_ACCEPTANCE=ENFORCED',
        'SCREENSHOT_GATE_REQUIRED=ENFORCED',
        'REJECT_EXCEL_REPAIR_PROMPT=ENFORCED',
        'PREUSSISCH_BLAU=#003153'
    )

    $missing = @($required | Where-Object { $Text -notlike ('*' + $_ + '*') })

    return [pscustomobject]@{
        Pass = ($missing.Count -eq 0)
        Missing = $missing
    }
}
