name: Linkcheck (HTMLProofer)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install Jekyll
        run: gem install jekyll --no-document

      - name: Build site (Jekyll)
        run: jekyll build --verbose --trace

      # htmlproofer bleibt absichtlich deaktiviert
      # wird im nächsten Schritt sauber aktiviert
